### ISSUE TITLE
Views nested within a <Text> must have a width and height

### ISSUE THREAD

**Issue by pandeyrohit51** [Benjamin-Dobell/react-native-markdown-view#10] opened 2017-10-17 08:48 UTC
I am using Markdown view inside a Text Element and it gives me the same error. I am using a plugin that truncates the text and adds 'Continue reading' . I am using Markdown inside it.

Code :

```
<View style={{flexDirection:'row',paddingBottom:5}}>
        <ReadMore
              numberOfLines={3}
              renderTruncatedFooter={this._renderTruncatedFooter}
              renderRevealedFooter={this._renderRevealedFooter}>
          <Text style={[styles.userInfoText,commonStyles.semiBoldText,commonStyles.smallText]}>
            <MarkdownView>{data}</MarkdownView>
          </Text>
        </ReadMore>
        </View> 
```
If i am giving the height and width the continue reading doesn't work properly.

Is there any way to render it using "rules" property. I am unable to get how to use the "rules" property.

And when i am using like this it displays an object  [object Object] in mobile

```
<View style={{flexDirection:'row',paddingBottom:5}}>
          <MarkdownView>
        <ReadMore
              numberOfLines={3}
              renderTruncatedFooter={this._renderTruncatedFooter}
              renderRevealedFooter={this._renderRevealedFooter}>
          <Text style={[styles.userInfoText,commonStyles.semiBoldText,commonStyles.smallText>{data}</Text>
        </ReadMore>
        </MarkdownView>
        </View>
```

**Comment by Benjamin-Dobell** [comment] 2017-10-18 00:51
Closing as duplicate of #5. Feel free to report anything you feel is relevant in that issue.

**Closed by Benjamin-Dobell** 2017-10-18 00:51 UTC
